// Code generated by entc, DO NOT EDIT.

package order

import (
	"fmt"
	"time"
)

const (
	// Label holds the string label denoting the order type in the database.
	Label = "order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldOrderDate holds the string denoting the orderdate field in the database.
	FieldOrderDate = "order_date"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"

	// EdgeOrderItems holds the string denoting the orderitems edge name in mutations.
	EdgeOrderItems = "orderItems"
	// EdgeDelivery holds the string denoting the delivery edge name in mutations.
	EdgeDelivery = "delivery"

	// Table holds the table name of the order in the database.
	Table = "orders"
	// OrderItemsTable is the table the holds the orderItems relation/edge.
	OrderItemsTable = "order_items"
	// OrderItemsInverseTable is the table name for the OrderItem entity.
	// It exists in this package in order to avoid circular dependency with the "orderitem" package.
	OrderItemsInverseTable = "order_items"
	// OrderItemsColumn is the table column denoting the orderItems relation/edge.
	OrderItemsColumn = "order_id"
	// DeliveryTable is the table the holds the delivery relation/edge.
	DeliveryTable = "orders"
	// DeliveryInverseTable is the table name for the Delivery entity.
	// It exists in this package in order to avoid circular dependency with the "delivery" package.
	DeliveryInverseTable = "delivery"
	// DeliveryColumn is the table column denoting the delivery relation/edge.
	DeliveryColumn = "delivery_id"
)

// Columns holds all SQL columns for order fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldOrderDate,
	FieldStatus,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Order type.
var ForeignKeys = []string{
	"delivery_id",
	"member_id",
}

var (
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the status enum field.
type Status string

// Status values.
const (
	StatusCANCEL Status = "CANCEL"
	StatusORDER  Status = "ORDER"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusCANCEL, StatusORDER:
		return nil
	default:
		return fmt.Errorf("order: invalid enum value for status field: %q", s)
	}
}
