// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Delivery is the predicate function for delivery builders.
type Delivery func(*sql.Selector)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// Member is the predicate function for member builders.
type Member func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// OrderItem is the predicate function for orderitem builders.
type OrderItem func(*sql.Selector)
